apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-deploy-test
spec:
  replicas: 1
  selector:
    matchLabels:
      run: music-test
  template:
    metadata:
      labels:
        run: music-test
    spec:
      containers:
        - image: 52.79.185.138/music/music:latest
          imagePullPolicy: Always
          name: music-test-pod
          ports:
          - containerPort: 80
